namespace Glass_Size_Estimator
{
	enum Configuration
	{
		NEO_PANEL,
		NOTCHED_INLINE_PANEL,
		ONE_INLINE_PANEL,
		RETURN_PANEL_135_DEGREE,
		RETURN_PANEL_90_DEGREE,
		TWO_INLINE_PANEL,
		TWO_PARTIAL_INLINE_PANEL
	}
}
